import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database with comprehensive AI Tools catalog across all categories and pricing models...');

  // Clear existing records
  await prisma.bookmark.deleteMany();
  await prisma.review.deleteMany();
  await prisma.tool.deleteMany();
  await prisma.user.deleteMany();

  const passwordHash = await bcrypt.hash('password123', 10);

  // Demo user for auth, reviews, and bookmarks
  const demoUser = await prisma.user.create({
    data: {
      name: 'Demo Reviewer',
      email: 'demo@aiorbit.club',
      passwordHash,
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      role: 'ADMIN',
    },
  });

  const toolsData = [
    // ==========================================
    // 1. CODING
    // ==========================================
    {
      name: 'Cursor',
      slug: 'cursor',
      tagLine: 'The AI-first code editor built for pair programming with frontier LLMs',
      description: 'Cursor is an advanced AI-native code editor forked from VS Code. Designed from the ground up for AI-first pair programming, it features multi-file autonomous editing via Composer, intelligent tab completions with Copilot++, codebase-wide semantic embeddings, and in-editor terminal debugging.',
      fullDescription: 'Cursor is an advanced AI-native code editor forked from VS Code. Designed from the ground up for AI-first pair programming, it features multi-file autonomous editing via Composer, intelligent tab completions with Copilot++, codebase-wide semantic embeddings, and in-editor terminal debugging.',
      category: 'Coding',
      pricing: 'Freemium',
      websiteUrl: 'https://cursor.com',
      url: 'https://cursor.com',
      rating: 4.9,
      reviewsCount: 384,
      iconUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Composer multi-file autonomous codebase editing',
        'Semantic codebase vector indexing and natural language symbol lookup',
        'Copilot++ intelligent inline tab autocomplete and prediction',
        'AI terminal diagnostics and command auto-fix',
        'Custom workspace rules (.cursorrules) for codebase standards',
      ]),
      useCases: JSON.stringify([
        'Full-stack TypeScript and Python application development',
        'Refactoring large, multi-module legacy codebases',
        'Instant terminal error diagnosis and automated patch generation',
        'Accelerated feature scaffolding and boilerplate elimination',
      ]),
      tags: JSON.stringify(['Code Editor', 'Developer Tools', 'VS Code', 'LLMs', 'Pair Programming']),
    },
    {
      name: 'GitHub Copilot',
      slug: 'github-copilot',
      tagLine: 'The world’s most widely adopted AI developer tool and pair programmer',
      description: 'GitHub Copilot turns natural language prompts into code across dozens of languages. Deeply integrated into VS Code, Visual Studio, Neovim, and JetBrains IDEs with Copilot Chat, pull request summaries, and multi-model switching.',
      fullDescription: 'GitHub Copilot turns natural language prompts into code across dozens of languages. Deeply integrated into VS Code, Visual Studio, Neovim, and JetBrains IDEs with Copilot Chat, pull request summaries, and multi-model switching.',
      category: 'Coding',
      pricing: 'Paid',
      websiteUrl: 'https://github.com/features/copilot',
      url: 'https://github.com/features/copilot',
      rating: 4.7,
      reviewsCount: 1540,
      iconUrl: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Context-aware code completion across 30+ programming languages',
        'Copilot Workspace for collaborative issue-to-PR workflows',
        'Multi-model selection including Claude 3.5 Sonnet, GPT-4o, and Gemini 1.5 Pro',
        'Automated pull request review summaries and security vulnerability detection',
        'CLI companion for shell commands and terminal script generation',
      ]),
      useCases: JSON.stringify([
        'Automating unit test and integration test generation',
        'Explaining complex algorithms and legacy code patterns',
        'Speeding up repetitive API scaffolding and boilerplate syntax',
        'Terminal command translation from plain English',
      ]),
      tags: JSON.stringify(['GitHub', 'Code Completion', 'Developer Tools', 'IDE', 'Enterprise']),
    },
    {
      name: 'Ollama',
      slug: 'ollama',
      tagLine: 'Get up and running with large language models locally on your own machine',
      description: 'Ollama is an open-source framework designed to run, customize, and build upon frontier open-source LLMs locally on macOS, Linux, and Windows. Run models like Llama 3.3, Mistral, Gemma, and DeepSeek-R1 with private, zero-latency inference.',
      fullDescription: 'Ollama is an open-source framework designed to run, customize, and build upon frontier open-source LLMs locally on macOS, Linux, and Windows. Run models like Llama 3.3, Mistral, Gemma, and DeepSeek-R1 with private, zero-latency inference.',
      category: 'Coding',
      pricing: 'Free',
      websiteUrl: 'https://ollama.com',
      url: 'https://ollama.com',
      rating: 4.9,
      reviewsCount: 820,
      iconUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Local execution of Llama 3, DeepSeek, Mistral, and Qwen models',
        'OpenAI-compatible local REST API endpoint',
        'Modelfile custom system prompts and parameter temperature tuning',
        'Hardware acceleration on Apple Silicon GPUs and NVIDIA CUDA',
      ]),
      useCases: JSON.stringify([
        'Completely air-gapped private LLM development and coding',
        'Local embeddings and offline RAG architectures',
        'Agentic terminal automation without cloud API tokens',
      ]),
      tags: JSON.stringify(['Open Source', 'Local LLM', 'Privacy', 'Developer Tools', 'Free']),
    },
    {
      name: 'DeepSeek Coder',
      slug: 'deepseek-coder',
      tagLine: 'High-performance open-source code intelligence and reasoning model',
      description: 'DeepSeek Coder is an open-weights coding foundation model pre-trained on 2 trillion tokens of code and natural language. It delivers exceptional coding benchmark scores, advanced project-level context understanding, and instant code synthesis.',
      fullDescription: 'DeepSeek Coder is an open-weights coding foundation model pre-trained on 2 trillion tokens of code and natural language. It delivers exceptional coding benchmark scores, advanced project-level context understanding, and instant code synthesis.',
      category: 'Coding',
      pricing: 'Free',
      websiteUrl: 'https://deepseek.com',
      url: 'https://deepseek.com',
      rating: 4.8,
      reviewsCount: 510,
      iconUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Fill-in-the-middle (FIM) code completion architecture',
        'Project-level repository awareness and cross-file resolution',
        'Free community API and open Hugging Face weights',
        'Multi-language support for over 80 programming languages',
      ]),
      useCases: JSON.stringify([
        'Self-hosted enterprise developer coding assistance',
        'Algorithmic problem solving and performance optimization',
        'Automated code migration across framework versions',
      ]),
      tags: JSON.stringify(['Open Source', 'Coding LLM', 'DeepSeek', 'Developer Tools', 'Free']),
    },
    {
      name: 'v0 by Vercel',
      slug: 'v0-vercel',
      tagLine: 'Generative UI system crafting accessible React and Tailwind components',
      description: 'v0 by Vercel is a generative user interface system powered by AI. It generates copy-paste friendly React components styled with Tailwind CSS and shadcn/ui from simple natural language prompts, expediting front-end product engineering.',
      fullDescription: 'v0 by Vercel is a generative user interface system powered by AI. It generates copy-paste friendly React components styled with Tailwind CSS and shadcn/ui from simple natural language prompts, expediting front-end product engineering.',
      category: 'Coding',
      pricing: 'Freemium',
      websiteUrl: 'https://v0.dev',
      url: 'https://v0.dev',
      rating: 4.8,
      reviewsCount: 640,
      iconUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Interactive preview sandbox with hot-reloading React rendering',
        'Export directly to Next.js, React, and Tailwind CSS codebases',
        'shadcn/ui and Radix accessibility component compliance',
        'Version branching and visual design variation iteration',
      ]),
      useCases: JSON.stringify([
        'Rapid landing page, dashboard, and interactive UI prototyping',
        'Design-to-code translation for modern SaaS applications',
        'Generating responsive forms, data tables, and navigation patterns',
      ]),
      tags: JSON.stringify(['Vercel', 'Generative UI', 'React', 'Tailwind CSS', 'Frontend']),
    },
    {
      name: 'Replit Agent',
      slug: 'replit-agent',
      tagLine: 'Autonomous AI software engineer that builds and deploys full-stack apps',
      description: 'Replit Agent is an autonomous AI developer that plans, codes, installs dependencies, debugs errors, and deploys full-stack production applications directly in cloud environments from simple natural language instructions.',
      fullDescription: 'Replit Agent is an autonomous AI developer that plans, codes, installs dependencies, debugs errors, and deploys full-stack production applications directly in cloud environments from simple natural language instructions.',
      category: 'Coding',
      pricing: 'Paid',
      websiteUrl: 'https://replit.com',
      url: 'https://replit.com',
      rating: 4.7,
      reviewsCount: 430,
      iconUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'End-to-end full-stack app construction from idea to deployment',
        'Automated database provisioning with PostgreSQL integration',
        'Self-healing runtime terminal debugging and execution verification',
        'Instant one-click custom domain hosting and SSL setup',
      ]),
      useCases: JSON.stringify([
        'Building and shipping MVP SaaS products in hours',
        'Automating internal team dashboards and tooling',
        'Rapid API server construction and third-party integrations',
      ]),
      tags: JSON.stringify(['Autonomous Agent', 'Cloud IDE', 'Deployment', 'Full-Stack']),
    },
    {
      name: 'Continue.dev',
      slug: 'continue-dev',
      tagLine: 'The leading open-source AI code assistant inside VS Code and JetBrains',
      description: 'Continue is the leading open-source AI code assistant. It allows developers to connect any commercial or local model (Ollama, Claude, GPT-4o) directly into their IDE for autocomplete, chat, and codebase understanding.',
      fullDescription: 'Continue is the leading open-source AI code assistant. It allows developers to connect any commercial or local model (Ollama, Claude, GPT-4o) directly into their IDE for autocomplete, chat, and codebase understanding.',
      category: 'Coding',
      pricing: 'Free',
      websiteUrl: 'https://continue.dev',
      url: 'https://continue.dev',
      rating: 4.8,
      reviewsCount: 310,
      iconUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Tab autocomplete with custom local or remote LLM backends',
        'Full codebase @Codebase indexing and context injection',
        'Support for custom slash commands and prompt templates',
        '100% open-source under Apache 2.0 license',
      ]),
      useCases: JSON.stringify([
        'Custom corporate IDE setup with self-hosted LLM endpoints',
        'Private in-IDE code reviews and refactoring suggestions',
        'Instant documentation lookup and unit test scaffolding',
      ]),
      tags: JSON.stringify(['Open Source', 'VS Code', 'JetBrains', 'Autocomplete', 'Free']),
    },

    // ==========================================
    // 2. TEXT & WRITING
    // ==========================================
    {
      name: 'ChatGPT',
      slug: 'chatgpt',
      tagLine: 'OpenAI conversational intelligence for reasoning, analysis, and generation',
      description: 'ChatGPT is OpenAI’s flagship conversational AI model powered by GPT-4o and o1 reasoning models. It excels at complex reasoning, document creation, data analysis, coding, and real-time voice interactions across personal and enterprise workflows.',
      fullDescription: 'ChatGPT is OpenAI’s flagship conversational AI model powered by GPT-4o and o1 reasoning models. It excels at complex reasoning, document creation, data analysis, coding, and real-time voice interactions across personal and enterprise workflows.',
      category: 'Text & Writing',
      pricing: 'Freemium',
      websiteUrl: 'https://chatgpt.com',
      url: 'https://chatgpt.com',
      rating: 4.8,
      reviewsCount: 1420,
      iconUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'OpenAI o1 and GPT-4o multimodal reasoning pipelines',
        'Interactive Canvas workspace for document & code collaboration',
        'Advanced Voice Mode with natural low-latency acoustic conversations',
        'Integrated Python execution sandbox and data interpreter',
        'Custom GPT store and personalized agent configuration',
      ]),
      useCases: JSON.stringify([
        'Deep scientific, technical, and mathematical reasoning',
        'Long-form editorial writing, copywriting, and documentation',
        'Exploratory data analysis and interactive chart generation',
        'Language translation and conversational knowledge assistance',
      ]),
      tags: JSON.stringify(['Conversational AI', 'Writing', 'Reasoning', 'Productivity', 'OpenAI']),
    },
    {
      name: 'Claude 3.5',
      slug: 'claude',
      tagLine: 'Next-generation AI assistant by Anthropic with groundbreaking coding and prose',
      description: 'Claude 3.5 Sonnet delivers industry-leading intelligence across coding, nuanced writing, and visual reasoning. Featuring an interactive Artifacts side-by-side workspace and a 200,000 token context window, Claude sets new benchmarks for software engineering and creative thinking.',
      fullDescription: 'Claude 3.5 Sonnet delivers industry-leading intelligence across coding, nuanced writing, and visual reasoning. Featuring an interactive Artifacts side-by-side workspace and a 200,000 token context window, Claude sets new benchmarks for software engineering and creative thinking.',
      category: 'Text & Writing',
      pricing: 'Freemium',
      websiteUrl: 'https://claude.ai',
      url: 'https://claude.ai',
      rating: 4.9,
      reviewsCount: 960,
      iconUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Interactive Artifacts for live React, HTML, and SVG rendering',
        '200,000-token context window for full-repository understanding',
        'Superior prose generation with human nuance and natural tone',
        'High-accuracy vision analysis for architecture schematics and diagrams',
        'Enterprise-grade safety, privacy, and constitutional alignment',
      ]),
      useCases: JSON.stringify([
        'Building interactive React UI components in Artifacts',
        'Drafting executive policy briefs and technical whitepapers',
        'Auditing massive codebase repositories and architecture diagrams',
        'Comprehensive pull request reviews and edge-case detection',
      ]),
      tags: JSON.stringify(['Anthropic', 'Artifacts', 'Writing', 'Reasoning', 'Frontier LLM']),
    },
    {
      name: 'Jasper AI',
      slug: 'jasper-ai',
      tagLine: 'Enterprise generative AI platform built for marketing and brand copywriting',
      description: 'Jasper is the enterprise generative AI platform built to help marketing teams create on-brand copy, blogs, social campaigns, and sales collateral with customizable brand voice guidelines and multi-channel campaign generation.',
      fullDescription: 'Jasper is the enterprise generative AI platform built to help marketing teams create on-brand copy, blogs, social campaigns, and sales collateral with customizable brand voice guidelines and multi-channel campaign generation.',
      category: 'Text & Writing',
      pricing: 'Paid',
      websiteUrl: 'https://jasper.ai',
      url: 'https://jasper.ai',
      rating: 4.6,
      reviewsCount: 780,
      iconUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Brand Voice knowledge base trained on style guides and positioning',
        'Multi-channel campaign generator across email, ads, and blog posts',
        'Plagiarism checker and SEO Surfer integration',
        'Team collaboration workspaces and approval workflows',
      ]),
      useCases: JSON.stringify([
        'End-to-end B2B marketing campaign content production',
        'SEO-optimized blog posts and product landing pages',
        'Social media copy variations across LinkedIn, X, and Facebook',
      ]),
      tags: JSON.stringify(['Copywriting', 'Marketing', 'Enterprise', 'Content Creation', 'SEO']),
    },
    {
      name: 'Grammarly AI',
      slug: 'grammarly-ai',
      tagLine: 'AI communication assistant for real-time grammar, tone, and clarity',
      description: 'Grammarly AI enhances writing everywhere you work. With one-click rewrites, tone detection, citation generation, and strategic sentence improvements, Grammarly ensures professional communication across web apps, emails, and documents.',
      fullDescription: 'Grammarly AI enhances writing everywhere you work. With one-click rewrites, tone detection, citation generation, and strategic sentence improvements, Grammarly ensures professional communication across web apps, emails, and documents.',
      category: 'Text & Writing',
      pricing: 'Freemium',
      websiteUrl: 'https://grammarly.com',
      url: 'https://grammarly.com',
      rating: 4.8,
      reviewsCount: 1650,
      iconUrl: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Real-time grammar, spelling, and punctuation correction',
        'Contextual tone detector and formal/casual style switcher',
        'Generative rewrites for conciseness and persuasive impact',
        'Browser extension and native desktop integration',
      ]),
      useCases: JSON.stringify([
        'Professional business email correspondence and proposals',
        'Academic paper proofreading and stylistic improvement',
        'Ensuring consistent corporate tone of voice in customer support',
      ]),
      tags: JSON.stringify(['Grammar', 'Editing', 'Communication', 'Productivity', 'Browser Extension']),
    },
    {
      name: 'HuggingChat',
      slug: 'huggingchat',
      tagLine: '100% Free, open-source conversational AI chat powered by top open weights',
      description: 'HuggingChat is Hugging Face’s open-source chat platform providing completely free access to leading open models including Llama 3.3, Command R+, Qwen 2.5, and DeepSeek, with live web search and custom assistant creation.',
      fullDescription: 'HuggingChat is Hugging Face’s open-source chat platform providing completely free access to leading open models including Llama 3.3, Command R+, Qwen 2.5, and DeepSeek, with live web search and custom assistant creation.',
      category: 'Text & Writing',
      pricing: 'Free',
      websiteUrl: 'https://huggingface.co/chat',
      url: 'https://huggingface.co/chat',
      rating: 4.7,
      reviewsCount: 420,
      iconUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Access to top open-weights models without registration fees',
        'Live web search integration for up-to-date factual queries',
        'Custom Assistants builder with tailored instructions and tools',
        'Zero data training on personal chats with privacy focus',
      ]),
      useCases: JSON.stringify([
        'Testing and evaluating different open-source LLM architectures',
        'General writing assistance, brainstorming, and translation',
        'Creating custom public or private AI assistants for community tasks',
      ]),
      tags: JSON.stringify(['Open Source', 'Hugging Face', 'Free AI', 'Chat', 'Privacy']),
    },
    {
      name: 'DeepL Translator',
      slug: 'deepl-translator',
      tagLine: 'The world’s most accurate AI translation and writing assistant',
      description: 'DeepL delivers neural machine translation that captures nuance, context, and idiomatic expressions across 30+ languages. With DeepL Write, users can refine grammar, style, and tone in multiple languages with unmatched precision.',
      fullDescription: 'DeepL delivers neural machine translation that captures nuance, context, and idiomatic expressions across 30+ languages. With DeepL Write, users can refine grammar, style, and tone in multiple languages with unmatched precision.',
      category: 'Text & Writing',
      pricing: 'Freemium',
      websiteUrl: 'https://deepl.com',
      url: 'https://deepl.com',
      rating: 4.9,
      reviewsCount: 1100,
      iconUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Neural machine translation with unmatched linguistic accuracy',
        'Document translation retaining original PDF, Word, and PPT formatting',
        'DeepL Write for tone and fluency polishing',
        'Custom glossary and term definitions for enterprise translation',
      ]),
      useCases: JSON.stringify([
        'Translating complex legal contracts and technical specifications',
        'Multilingual website and product copy localization',
        'Global business team email and chat correspondence',
      ]),
      tags: JSON.stringify(['Translation', 'Language', 'Localization', 'Writing', 'DeepL']),
    },
    {
      name: 'Sudowrite',
      slug: 'sudowrite',
      tagLine: 'The non-judgmental AI writing partner designed specifically for creative writers',
      description: 'Sudowrite is an AI novel writing and storytelling assistant. Built specifically for fiction writers, it helps overcome writer’s block with sensory descriptions, chapter pacing, character development, and plot twist ideation.',
      fullDescription: 'Sudowrite is an AI novel writing and storytelling assistant. Built specifically for fiction writers, it helps overcome writer’s block with sensory descriptions, chapter pacing, character development, and plot twist ideation.',
      category: 'Text & Writing',
      pricing: 'Paid',
      websiteUrl: 'https://sudowrite.com',
      url: 'https://sudowrite.com',
      rating: 4.7,
      reviewsCount: 390,
      iconUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Story Engine for chapter-by-chapter novel generation and drafting',
        'Sensory description expander for smell, touch, and sound',
        'Brainstorming mode for character arcs, names, and plot twists',
        'Rewrite tool for pacing, dialogue enhancement, and show-dont-tell',
      ]),
      useCases: JSON.stringify([
        'Writing full-length fiction novels and fantasy series',
        'Screenplay and dramatic narrative outlining',
        'Overcoming creative writer’s block with interactive prose branches',
      ]),
      tags: JSON.stringify(['Creative Writing', 'Fiction', 'Novels', 'Story Engine', 'Paid']),
    },

    // ==========================================
    // 3. IMAGE GENERATION
    // ==========================================
    {
      name: 'Midjourney',
      slug: 'midjourney',
      tagLine: 'State-of-the-art generative image model renowned for artistic brilliance and realism',
      description: 'Midjourney is an independent research lab exploring new mediums of thought. Its diffusion model produces breathtaking, photorealistic and stylized imagery from natural language prompts, prized by artists, concept designers, and art directors worldwide.',
      fullDescription: 'Midjourney is an independent research lab exploring new mediums of thought. Its diffusion model produces breathtaking, photorealistic and stylized imagery from natural language prompts, prized by artists, concept designers, and art directors worldwide.',
      category: 'Image Generation',
      pricing: 'Paid',
      websiteUrl: 'https://midjourney.com',
      url: 'https://midjourney.com',
      rating: 4.9,
      reviewsCount: 1120,
      iconUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Cinematic photorealism and stylistic artistic versatility',
        'Inpainting, pan, zoom out, and vary region canvas controls',
        'Character and style reference consistency parameters (--cref / --sref)',
        'High-resolution upscaling with custom aspect ratios',
        'Web-based creation canvas and community inspiration explorer',
      ]),
      useCases: JSON.stringify([
        'Concept art and mood board creation for cinema and video games',
        'High-end visual branding and advertising key visual design',
        'Photorealistic 3D product renders and architectural mockups',
        'Editorial book covers and magazine illustration',
      ]),
      tags: JSON.stringify(['Art', 'Diffusion', 'Photorealism', 'Concept Art', 'Design']),
    },
    {
      name: 'Stable Diffusion 3.5',
      slug: 'stable-diffusion',
      tagLine: 'Open weights text-to-image foundation model by Stability AI',
      description: 'Stable Diffusion 3.5 delivers state-of-the-art image quality, exceptional prompt adherence, and typography rendering in open weights for consumer hardware and cloud deployments.',
      fullDescription: 'Stable Diffusion 3.5 delivers state-of-the-art image quality, exceptional prompt adherence, and typography rendering in open weights for consumer hardware and cloud deployments.',
      category: 'Image Generation',
      pricing: 'Freemium',
      websiteUrl: 'https://stability.ai',
      url: 'https://stability.ai',
      rating: 4.7,
      reviewsCount: 890,
      iconUrl: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Multimodal Diffusion Transformer (MMDiT) architecture',
        'Advanced typography rendering and text generation in images',
        'Custom fine-tuning via LoRA and ControlNet pipelines',
        'Available in Large (8B) and Medium parameter variants',
      ]),
      useCases: JSON.stringify([
        'Custom local image generation pipelines and game asset creation',
        'Commercial product mockups with fine-tuned enterprise LoRAs',
        'Creative graphic design with accurate typography integration',
      ]),
      tags: JSON.stringify(['Open Weights', 'Stability AI', 'Text-to-Image', 'Design', 'Generative']),
    },
    {
      name: 'Flux.1',
      slug: 'flux-1',
      tagLine: 'Next-generation open-weights image generation by Black Forest Labs',
      description: 'Flux.1 is the cutting-edge 12-billion parameter image foundation model created by the original Stable Diffusion inventors. It delivers world-class anatomy rendering, complex prompt adherence, and photorealism completely free in open weights.',
      fullDescription: 'Flux.1 is the cutting-edge 12-billion parameter image foundation model created by the original Stable Diffusion inventors. It delivers world-class anatomy rendering, complex prompt adherence, and photorealism completely free in open weights.',
      category: 'Image Generation',
      pricing: 'Free',
      websiteUrl: 'https://blackforestlabs.ai',
      url: 'https://blackforestlabs.ai',
      rating: 4.9,
      reviewsCount: 670,
      iconUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        '12B parameter hybrid architecture with rotary positional embeddings',
        'Unmatched human hand and skin texture rendering',
        'Flawless in-image typography and complex multi-object composition',
        'Schnell (fast 4-step) and Dev open-source model weights',
      ]),
      useCases: JSON.stringify([
        'Photorealistic portrait and fashion photography generation',
        'High-resolution promotional poster and album artwork design',
        'Self-hosted commercial image generation backends',
      ]),
      tags: JSON.stringify(['Open Source', 'Black Forest Labs', 'Flux', 'Free', 'State of the Art']),
    },
    {
      name: 'Recraft',
      slug: 'recraft',
      tagLine: 'AI graphic design engine generating vector SVG art, 3D graphics, and icons',
      description: 'Recraft is an AI-powered design generator built specifically for professional designers. It generates infinite-resolution vector SVG graphics, cohesive 3D icon sets, and vector illustrations with strict brand color palette controls.',
      fullDescription: 'Recraft is an AI-powered design generator built specifically for professional designers. It generates infinite-resolution vector SVG graphics, cohesive 3D icon sets, and vector illustrations with strict brand color palette controls.',
      category: 'Image Generation',
      pricing: 'Free',
      websiteUrl: 'https://recraft.ai',
      url: 'https://recraft.ai',
      rating: 4.8,
      reviewsCount: 520,
      iconUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Native infinite-resolution Vector SVG export',
        'Color palette locking with exact HEX brand code enforcement',
        'Icon pack generation with matching stroke widths and style consistency',
        'Inpainting, background eraser, and vector layer splitting',
      ]),
      useCases: JSON.stringify([
        'Creating scalable SVG icons and illustrations for web apps',
        'Designing 3D app icons and marketing collateral',
        'Branded design system asset generation for Figma workflows',
      ]),
      tags: JSON.stringify(['Vector', 'SVG', 'Design System', 'Icons', 'Free']),
    },
    {
      name: 'Adobe Firefly',
      slug: 'adobe-firefly',
      tagLine: 'Commercial-safe generative AI integrated into Photoshop and Illustrator',
      description: 'Adobe Firefly is Adobe’s family of creative generative AI models. Designed to be commercially safe and trained on licensed Adobe Stock content, it powers Generative Fill, Generative Expand, and Text to Vector across Creative Cloud.',
      fullDescription: 'Adobe Firefly is Adobe’s family of creative generative AI models. Designed to be commercially safe and trained on licensed Adobe Stock content, it powers Generative Fill, Generative Expand, and Text to Vector across Creative Cloud.',
      category: 'Image Generation',
      pricing: 'Paid',
      websiteUrl: 'https://firefly.adobe.com',
      url: 'https://firefly.adobe.com',
      rating: 4.6,
      reviewsCount: 710,
      iconUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Generative Fill directly inside Adobe Photoshop',
        'Commercially safe indemnity protection for enterprise use',
        'Text to Vector graphic creation inside Adobe Illustrator',
        'Structure and Style Reference controls matching brand imagery',
      ]),
      useCases: JSON.stringify([
        'Commercial advertising photography touch-ups and element replacement',
        'Vector pattern and branding creation in Illustrator',
        'Extending canvas borders and aspect ratio resizing for banner ads',
      ]),
      tags: JSON.stringify(['Adobe', 'Photoshop', 'Commercial Safe', 'Design', 'Paid']),
    },

    // ==========================================
    // 4. AUDIO
    // ==========================================
    {
      name: 'ElevenLabs',
      slug: 'elevenlabs',
      tagLine: 'The world’s most versatile AI voice generator and text-to-speech platform',
      description: 'ElevenLabs brings stories to life with realistic, versatile, and contextually aware AI voices. Supporting 32 languages, voice cloning, emotional inflection, and dubbing, it powers audiobooks, gaming, video narration, and conversational agents.',
      fullDescription: 'ElevenLabs brings stories to life with realistic, versatile, and contextually aware AI voices. Supporting 32 languages, voice cloning, emotional inflection, and dubbing, it powers audiobooks, gaming, video narration, and conversational agents.',
      category: 'Audio',
      pricing: 'Freemium',
      websiteUrl: 'https://elevenlabs.io',
      url: 'https://elevenlabs.io',
      rating: 4.9,
      reviewsCount: 1240,
      iconUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Hyper-realistic voice synthesis across 32 languages',
        'Instant voice cloning with 1-minute audio sample',
        'Conversational AI voice agents with sub-second websocket latency',
        'AI Sound Effects generator for games and films',
        'Automated video dubbing preserving original speaker tone and cadence',
      ]),
      useCases: JSON.stringify([
        'High-end audiobook narration and dynamic podcast voice tracks',
        'Multilingual video localization with lip-sync alignment',
        'Interactive real-time voice bots and customer service agents',
        'Game character voice acting with emotional pacing',
      ]),
      tags: JSON.stringify(['Voice Synthesis', 'TTS', 'Audio', 'Voice Cloning', 'Localization']),
    },
    {
      name: 'Suno AI',
      slug: 'suno-ai',
      tagLine: 'Create full-length, broadcast-quality songs and music from simple text prompts',
      description: 'Suno is a generative audio model that generates full-length, broadcast-quality musical compositions complete with acoustic instruments, lyrical vocals, harmonies, and genre styling in seconds from natural language descriptions.',
      fullDescription: 'Suno is a generative audio model that generates full-length, broadcast-quality musical compositions complete with acoustic instruments, lyrical vocals, harmonies, and genre styling in seconds from natural language descriptions.',
      category: 'Audio',
      pricing: 'Freemium',
      websiteUrl: 'https://suno.com',
      url: 'https://suno.com',
      rating: 4.8,
      reviewsCount: 790,
      iconUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Full 4-minute song generation with verses, chorus, and bridges',
        'Custom lyrics upload and genre fusion prompting (e.g. synthwave jazz)',
        'Audio stem separation for vocals, bass, drums, and instruments',
        'Inpainting to replace or extend specific song sections',
      ]),
      useCases: JSON.stringify([
        'Custom royalty-free background music for YouTube and commercials',
        'Interactive songwriting and melody brainstorming',
        'Video game soundtrack composition and thematic scoring',
      ]),
      tags: JSON.stringify(['Music Generation', 'Audio', 'Generative Music', 'Songs', 'Vocals']),
    },
    {
      name: 'OpenAI Whisper',
      slug: 'whisper',
      tagLine: 'Robust speech recognition and multilingual audio translation system',
      description: 'Whisper is a state-of-the-art speech recognition system trained on 680,000 hours of multilingual audio. It delivers human-level transcription, language identification, and English translation across diverse accents and noisy environments.',
      fullDescription: 'Whisper is a state-of-the-art speech recognition system trained on 680,000 hours of multilingual audio. It delivers human-level transcription, language identification, and English translation across diverse accents and noisy environments.',
      category: 'Audio',
      pricing: 'Free',
      websiteUrl: 'https://openai.com/research/whisper',
      url: 'https://openai.com/research/whisper',
      rating: 4.9,
      reviewsCount: 760,
      iconUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Multilingual automatic speech recognition across 99+ languages',
        'Real-time acoustic noise robustness and punctuation restoration',
        'Direct speech-to-English translation pipeline',
        'Compact quantized models for edge device execution',
      ]),
      useCases: JSON.stringify([
        'Automated podcast and video subtitle timestamp generation',
        'Clinical and court audio transcription pipelines',
        'Voice user interface input parsing for embedded systems',
      ]),
      tags: JSON.stringify(['Speech Recognition', 'Audio', 'OpenAI', 'Transcription', 'Free']),
    },
    {
      name: 'Murf.ai',
      slug: 'murf-ai',
      tagLine: 'Studio-quality AI voice generator for corporate videos and e-learning',
      description: 'Murf.ai provides studio-quality AI voiceovers with customizable pitch, speed, emphasis, and background music syncing. Trusted by Fortune 500 teams for product demos, presentations, and training modules.',
      fullDescription: 'Murf.ai provides studio-quality AI voiceovers with customizable pitch, speed, emphasis, and background music syncing. Trusted by Fortune 500 teams for product demos, presentations, and training modules.',
      category: 'Audio',
      pricing: 'Paid',
      websiteUrl: 'https://murf.ai',
      url: 'https://murf.ai',
      rating: 4.7,
      reviewsCount: 540,
      iconUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Over 120+ natural sounding AI voices in 20+ languages',
        'Fine-grained pitch, speed, and pause duration controls',
        'Voice-to-voice transformation replacing raw recordings with AI studio sound',
        'Commercial usage rights and royalty-free background soundtrack library',
      ]),
      useCases: JSON.stringify([
        'Corporate training videos and e-learning instructional modules',
        'SaaS explainer videos and product launch voiceovers',
        'Audio advertisements and broadcast television commercials',
      ]),
      tags: JSON.stringify(['Voiceover', 'TTS', 'E-Learning', 'Corporate Audio', 'Paid']),
    },
    {
      name: 'AudioCraft by Meta',
      slug: 'audiocraft',
      tagLine: 'Open-source generative audio research framework by Meta AI',
      description: 'AudioCraft is Meta’s open-source deep learning library for generating high-quality music, sound effects, and acoustic textures. Comprising MusicGen, AudioGen, and EnCodec, it gives researchers full control over sound synthesis.',
      fullDescription: 'AudioCraft is Meta’s open-source deep learning library for generating high-quality music, sound effects, and acoustic textures. Comprising MusicGen, AudioGen, and EnCodec, it gives researchers full control over sound synthesis.',
      category: 'Audio',
      pricing: 'Free',
      websiteUrl: 'https://github.com/facebookresearch/audiocraft',
      url: 'https://github.com/facebookresearch/audiocraft',
      rating: 4.8,
      reviewsCount: 380,
      iconUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'MusicGen controllable music generation with text or melody conditioning',
        'AudioGen realistic sound effects from text descriptions',
        'EnCodec high-fidelity neural audio compression',
        'Completely open-source PyTorch code and model weights',
      ]),
      useCases: JSON.stringify([
        'Generating Foley sound effects for indie video games',
        'Academic audio generation and generative acoustic research',
        'Custom local music composition pipelines without cloud costs',
      ]),
      tags: JSON.stringify(['Open Source', 'Meta AI', 'MusicGen', 'PyTorch', 'Free']),
    },

    // ==========================================
    // 5. VIDEO
    // ==========================================
    {
      name: 'Runway Gen-3 Alpha',
      slug: 'runway',
      tagLine: 'Pioneering frontier video generation model and creative world builder',
      description: 'Runway Gen-3 Alpha is a foundational video model capable of generating high-fidelity, controllable video clips with complex cinematic camera motions, expressive character actions, and photorealistic physics simulations.',
      fullDescription: 'Runway Gen-3 Alpha is a foundational video model capable of generating high-fidelity, controllable video clips with complex cinematic camera motions, expressive character actions, and photorealistic physics simulations.',
      category: 'Video',
      pricing: 'Paid',
      websiteUrl: 'https://runwayml.com',
      url: 'https://runwayml.com',
      rating: 4.8,
      reviewsCount: 880,
      iconUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Text-to-Video and Image-to-Video high temporal consistency generation',
        'Motion Brush with multi-directional trajectory and speed control',
        'Camera Control: zoom, pan, tilt, truck, and cinematic roll paths',
        'Director Mode with precise visual framing and lighting cues',
        'Lip-sync audio performance matching video characters',
      ]),
      useCases: JSON.stringify([
        'Cinematic film pre-visualization and concept trailer creation',
        'High-production music video sequences and visual effects',
        'Commercial advertising B-roll generation and brand vignettes',
        'Dynamic social media motion graphics and title cards',
      ]),
      tags: JSON.stringify(['Video Generation', 'Cinematography', 'VFX', 'World Models', 'Gen-3']),
    },
    {
      name: 'Pika 2.0',
      slug: 'pika-ai',
      tagLine: 'Idea-to-video platform with special effects, physics, and lip syncing',
      description: 'Pika 2.0 is an intuitive AI video platform that turns text, images, and existing clips into expressive 3D and cinematic video. With Pikaffects (inflate, melt, crush, explode) and smart sound effects, Pika makes video creation viral and effortless.',
      fullDescription: 'Pika 2.0 is an intuitive AI video platform that turns text, images, and existing clips into expressive 3D and cinematic video. With Pikaffects (inflate, melt, crush, explode) and smart sound effects, Pika makes video creation viral and effortless.',
      category: 'Video',
      pricing: 'Freemium',
      websiteUrl: 'https://pika.art',
      url: 'https://pika.art',
      rating: 4.7,
      reviewsCount: 620,
      iconUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Pikaffects: physics-bending simulations (melt, explode, squish, slice)',
        'Image-to-video with seamless motion flow and particle dynamics',
        'Inpainting to modify specific regions of existing video frames',
        'Automated generative sound effects synced to video motion',
      ]),
      useCases: JSON.stringify([
        'Viral social media video shorts for TikTok and Instagram Reels',
        'Creative brand product reveal animations and 3D effects',
        'Fast conceptual storytelling and animated character vignettes',
      ]),
      tags: JSON.stringify(['Video Generation', 'Special Effects', 'Animation', 'Social Media', 'Freemium']),
    },
    {
      name: 'Synthesia',
      slug: 'synthesia',
      tagLine: 'AI video avatars and multilingual corporate training video platform',
      description: 'Synthesia transforms text into professional presenter-led videos in minutes. Featuring 160+ diverse AI avatars and 130+ languages, it eliminates traditional cameras, microphones, and studio production costs for global teams.',
      fullDescription: 'Synthesia transforms text into professional presenter-led videos in minutes. Featuring 160+ diverse AI avatars and 130+ languages, it eliminates traditional cameras, microphones, and studio production costs for global teams.',
      category: 'Video',
      pricing: 'Paid',
      websiteUrl: 'https://synthesia.io',
      url: 'https://synthesia.io',
      rating: 4.8,
      reviewsCount: 910,
      iconUrl: 'https://images.unsplash.com/photo-1579208575657-c595a053b977?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1579208575657-c595a053b977?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        '160+ photorealistic digital AI presenters with natural body gestures',
        'Multilingual voice synthesis in 130+ languages with perfect lip sync',
        'Custom corporate avatar generation using personal video footage',
        'Interactive screen recorder and slide deck import',
      ]),
      useCases: JSON.stringify([
        'Enterprise employee onboarding and compliance training videos',
        'Customer success product tutorials and SaaS onboarding',
        'Global sales enablement and multilingual marketing messages',
      ]),
      tags: JSON.stringify(['AI Avatars', 'Corporate Video', 'Training', 'Multilingual', 'Paid']),
    },
    {
      name: 'Stable Video Diffusion',
      slug: 'stable-video-diffusion',
      tagLine: 'State-of-the-art open-source image-to-video diffusion model',
      description: 'Stable Video Diffusion is Stability AI’s open-weights video model capable of generating high-resolution video frames from static images, providing developers and researchers a completely free foundation for local video generation.',
      fullDescription: 'Stable Video Diffusion is Stability AI’s open-weights video model capable of generating high-resolution video frames from static images, providing developers and researchers a completely free foundation for local video generation.',
      category: 'Video',
      pricing: 'Free',
      websiteUrl: 'https://stability.ai/stable-video',
      url: 'https://stability.ai/stable-video',
      rating: 4.6,
      reviewsCount: 440,
      iconUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'High-resolution 576x1024 video frame generation at up to 30 fps',
        'Multi-view 3D camera synthesis from single input images',
        'Completely open weights on Hugging Face for local GPU execution',
        'ComfyUI node workflows for fine-grained video pipeline control',
      ]),
      useCases: JSON.stringify([
        'Local, private image animation and 3D asset camera turns',
        'Academic video generation and motion interpolation research',
        'Building custom generative video web apps without cloud API bills',
      ]),
      tags: JSON.stringify(['Open Source', 'Video Diffusion', 'Stability AI', 'Free', 'Image to Video']),
    },

    // ==========================================
    // 6. PRODUCTIVITY
    // ==========================================
    {
      name: 'Notion AI',
      slug: 'notion-ai',
      tagLine: 'Connected AI assistant integrated directly across notes, docs, and wikis',
      description: 'Notion AI turns your connected workspace into an intelligent knowledge brain. It summarizes complex documentation, writes first drafts, analyzes multi-table databases, and answers questions across your entire company wiki.',
      fullDescription: 'Notion AI turns your connected workspace into an intelligent knowledge brain. It summarizes complex documentation, writes first drafts, analyzes multi-table databases, and answers questions across your entire company wiki.',
      category: 'Productivity',
      pricing: 'Freemium',
      websiteUrl: 'https://notion.so',
      url: 'https://notion.so',
      rating: 4.8,
      reviewsCount: 1350,
      iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Q&A searching across entire team knowledge bases and connected Slack',
        'AI autofill properties in databases and relational project tables',
        'In-place text improvement, tone adjustments, and translation',
        'Automatic meeting summary and action item extraction',
      ]),
      useCases: JSON.stringify([
        'Internal company wiki Q&A and employee onboarding answers',
        'Extracting action items and owners from meeting transcriptions',
        'Automated database summaries for product feedback and bug trackers',
      ]),
      tags: JSON.stringify(['Productivity', 'Knowledge Base', 'Notes', 'Workplace', 'Notion']),
    },
    {
      name: 'Superhuman AI',
      slug: 'superhuman-ai',
      tagLine: 'The fastest email experience ever made, powered by generative AI',
      description: 'Superhuman AI writes emails in your voice, summarizes long conversation threads in one line, and turns rough thoughts into polished replies, saving busy executives and founders over 4 hours every week.',
      fullDescription: 'Superhuman AI writes emails in your voice, summarizes long conversation threads in one line, and turns rough thoughts into polished replies, saving busy executives and founders over 4 hours every week.',
      category: 'Productivity',
      pricing: 'Paid',
      websiteUrl: 'https://superhuman.com',
      url: 'https://superhuman.com',
      rating: 4.9,
      reviewsCount: 680,
      iconUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Instant AI reply drafting calibrated to your personal writing style',
        'One-line conversation summaries highlighting urgency and deadlines',
        'Split Inbox automated prioritization for high-value VIPs',
        'Blazing fast keyboard shortcuts under 100ms response latency',
      ]),
      useCases: JSON.stringify([
        'Executive inbox triage and high-volume email delegation',
        'Rapid investor and customer relationship email management',
        'Drafting persuasive sales outreach in seconds',
      ]),
      tags: JSON.stringify(['Email', 'Productivity', 'Executive', 'Fast', 'Paid']),
    },
    {
      name: 'Obsidian Smart Connections',
      slug: 'obsidian-smart-connections',
      tagLine: 'Open-source local AI knowledge graph and vector search for Obsidian notes',
      description: 'Smart Connections is an open-source AI plugin for Obsidian. It embeds your markdown notes locally into a vector database, finding unexpected connections, related thoughts, and answering queries with zero cloud privacy leaks.',
      fullDescription: 'Smart Connections is an open-source AI plugin for Obsidian. It embeds your markdown notes locally into a vector database, finding unexpected connections, related thoughts, and answering queries with zero cloud privacy leaks.',
      category: 'Productivity',
      pricing: 'Free',
      websiteUrl: 'https://github.com/brianpetro/obsidian-smart-connections',
      url: 'https://github.com/brianpetro/obsidian-smart-connections',
      rating: 4.8,
      reviewsCount: 410,
      iconUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Local vector embeddings indexing your entire Obsidian vault',
        'Real-time notes recommendation showing related concepts as you type',
        'Interactive Chat mode querying all personal journal entries and notes',
        '100% private local execution compatible with Ollama and LM Studio',
      ]),
      useCases: JSON.stringify([
        'Second Brain knowledge retrieval and thesis research linking',
        'Finding forgotten concepts and interconnected ideas across thousands of notes',
        'Private journaling and personal reflection synthesis',
      ]),
      tags: JSON.stringify(['Open Source', 'Obsidian', 'Second Brain', 'Local AI', 'Free']),
    },
    {
      name: 'Otter.ai',
      slug: 'otter-ai',
      tagLine: 'AI meeting assistant recording audio, writing notes, and extracting action items',
      description: 'Otter.ai automatically joins Zoom, Google Meet, and Microsoft Teams meetings to transcribe conversations in real-time, summarize discussion highlights, and assign action items to attendees.',
      fullDescription: 'Otter.ai automatically joins Zoom, Google Meet, and Microsoft Teams meetings to transcribe conversations in real-time, summarize discussion highlights, and assign action items to attendees.',
      category: 'Productivity',
      pricing: 'Freemium',
      websiteUrl: 'https://otter.ai',
      url: 'https://otter.ai',
      rating: 4.7,
      reviewsCount: 940,
      iconUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Real-time meeting audio transcription with speaker diarization',
        'OtterPilot auto-joining scheduled calendar calls',
        'Automated 30-second post-meeting summary emails with action items',
        'Interactive Q&A asking questions about past team meetings',
      ]),
      useCases: JSON.stringify([
        'Capturing detailed client discovery calls and design requirements',
        'Sharing asynchronous meeting recaps with remote team members',
        'Interview transcription for hiring and qualitative customer research',
      ]),
      tags: JSON.stringify(['Meetings', 'Transcription', 'Notes', 'Collaboration', 'Freemium']),
    },

    // ==========================================
    // 7. MARKETING OPS
    // ==========================================
    {
      name: 'AdCreative.ai',
      slug: 'adcreative-ai',
      tagLine: 'Generate conversion-focused ad banners, copy, and videos with AI',
      description: 'AdCreative.ai uses machine learning trained on millions of high-performing ads to generate conversion-optimized ad creatives, headlines, and social media banners that dramatically boost click-through rates and ROAS.',
      fullDescription: 'AdCreative.ai uses machine learning trained on millions of high-performing ads to generate conversion-optimized ad creatives, headlines, and social media banners that dramatically boost click-through rates and ROAS.',
      category: 'Marketing Ops',
      pricing: 'Paid',
      websiteUrl: 'https://adcreative.ai',
      url: 'https://adcreative.ai',
      rating: 4.7,
      reviewsCount: 650,
      iconUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'AI banner generation scoring creatives by conversion probability',
        'Multi-size export for Meta, Google Ads, TikTok, and LinkedIn formats',
        'Competitor ad intelligence and creative benchmarking',
        'High-converting sales copy generation for headlines and descriptions',
      ]),
      useCases: JSON.stringify([
        'Scaling paid advertising campaigns across Facebook and Google',
        'Rapid A/B creative testing with dozens of visual variations',
        'E-commerce product promotion banners and seasonal sale designs',
      ]),
      tags: JSON.stringify(['Advertising', 'Marketing', 'Conversion', 'Banners', 'ROAS']),
    },
    {
      name: 'Jasper Marketing Hub',
      slug: 'jasper-marketing-hub',
      tagLine: 'Multi-channel marketing campaign orchestration with custom brand voice',
      description: 'Jasper Marketing Hub centralizes brand voice assets, product knowledge, and SEO strategies to autonomously draft entire cross-channel marketing campaigns spanning landing pages, emails, social posts, and ad copy.',
      fullDescription: 'Jasper Marketing Hub centralizes brand voice assets, product knowledge, and SEO strategies to autonomously draft entire cross-channel marketing campaigns spanning landing pages, emails, social posts, and ad copy.',
      category: 'Marketing Ops',
      pricing: 'Paid',
      websiteUrl: 'https://jasper.ai',
      url: 'https://jasper.ai',
      rating: 4.8,
      reviewsCount: 510,
      iconUrl: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Unified Brand Knowledge Base syncing style guides and product specs',
        'Full campaign generation orchestrating 10+ marketing deliverables at once',
        'Performance analytics tracking high-engagement messaging patterns',
        'Enterprise security, SOC2 compliance, and zero data model training',
      ]),
      useCases: JSON.stringify([
        'Quarterly product launch marketing asset production',
        'Global brand consistency across distributed regional marketing teams',
        'Automated demand generation campaign scaling',
      ]),
      tags: JSON.stringify(['Marketing Ops', 'Campaigns', 'Brand Voice', 'Content Ops', 'Enterprise']),
    },
    {
      name: 'Surfer SEO',
      slug: 'surfer-seo',
      tagLine: 'AI-driven content optimization and organic search ranking engine',
      description: 'Surfer analyzes top-ranking Google search results to provide real-time recommendations for keyword density, headings, article structure, and internal linking to rank articles on page 1 of search engines.',
      fullDescription: 'Surfer analyzes top-ranking Google search results to provide real-time recommendations for keyword density, headings, article structure, and internal linking to rank articles on page 1 of search engines.',
      category: 'Marketing Ops',
      pricing: 'Paid',
      websiteUrl: 'https://surferseo.com',
      url: 'https://surferseo.com',
      rating: 4.8,
      reviewsCount: 720,
      iconUrl: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Real-time Content Score benchmarked against top 10 SERP competitors',
        'Keyword research tool uncovering high-opportunity organic clusters',
        'AI Article Generator drafting fully optimized long-form articles',
        'Automated Internal Linking and website content auditing',
      ]),
      useCases: JSON.stringify([
        'Scaling organic blog traffic and top-of-funnel inbound leads',
        'Auditing and refreshing declining organic website pages',
        'Creating comprehensive SEO content briefs for freelance writers',
      ]),
      tags: JSON.stringify(['SEO', 'Marketing Ops', 'Content Strategy', 'Google SERP', 'Paid']),
    },
    {
      name: 'Google GA4 AI Insights',
      slug: 'ga4-ai-insights',
      tagLine: 'Automated predictive audience analytics and anomaly detection by Google',
      description: 'Google Analytics 4 utilizes machine learning to surface automated insights, predict user churn and purchase probability, detect sudden traffic anomalies, and provide custom recommendations for marketing attribution.',
      fullDescription: 'Google Analytics 4 utilizes machine learning to surface automated insights, predict user churn and purchase probability, detect sudden traffic anomalies, and provide custom recommendations for marketing attribution.',
      category: 'Marketing Ops',
      pricing: 'Free',
      websiteUrl: 'https://analytics.google.com',
      url: 'https://analytics.google.com',
      rating: 4.6,
      reviewsCount: 1200,
      iconUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Predictive metrics: purchase probability, churn probability, and revenue prediction',
        'Automated anomaly detection alerting on unexpected traffic spikes or drops',
        'Cross-platform conversion modeling across web and mobile apps',
        '100% free enterprise-grade web traffic analytics suite',
      ]),
      useCases: JSON.stringify([
        'Building high-intent audience segments for Google Ads remarketing',
        'Monitoring conversion funnel drop-offs and marketing channel attribution',
        'Detecting technical tracking glitches or sudden traffic spikes',
      ]),
      tags: JSON.stringify(['Analytics', 'Google', 'Marketing Ops', 'Predictive AI', 'Free']),
    },
    {
      name: 'Writesonic Ops',
      slug: 'writesonic-ops',
      tagLine: 'AI article writer, landing page copy, and SEO content platform',
      description: 'Writesonic generates SEO-optimized articles, landing pages, Google ads, and product descriptions powered by GPT-4o and real-time Google search data.',
      fullDescription: 'Writesonic generates SEO-optimized articles, landing pages, Google ads, and product descriptions powered by GPT-4o and real-time Google search data.',
      category: 'Marketing Ops',
      pricing: 'Freemium',
      websiteUrl: 'https://writesonic.com',
      url: 'https://writesonic.com',
      rating: 4.7,
      reviewsCount: 580,
      iconUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Article Writer 6.0 with live web citations and competitive analysis',
        'One-click WordPress and Shopify publishing integration',
        'Chatsonic conversational AI assistant with live Google data',
        'Landing page copywriting with customizable tone and call-to-actions',
      ]),
      useCases: JSON.stringify([
        'Publishing high-frequency blog content for inbound marketing',
        'Generating product descriptions for large e-commerce catalogs',
        'Social media caption batches and promotional newsletters',
      ]),
      tags: JSON.stringify(['Marketing', 'SEO', 'Copywriting', 'Content Ops', 'Freemium']),
    },

    // ==========================================
    // 8. DEEP RESEARCH
    // ==========================================
    {
      name: 'Perplexity AI',
      slug: 'perplexity-ai',
      tagLine: 'The conversational AI answer engine delivering direct answers with live web citations',
      description: 'Perplexity AI revolutionizes information discovery by combining frontier large language models with real-time web search. It delivers synthesized answers supported by inline, clickable citations, eliminating SEO spam and halluncinations.',
      fullDescription: 'Perplexity AI revolutionizes information discovery by combining frontier large language models with real-time web search. It delivers synthesized answers supported by inline, clickable citations, eliminating SEO spam and halluncinations.',
      category: 'Deep Research',
      pricing: 'Freemium',
      websiteUrl: 'https://perplexity.ai',
      url: 'https://perplexity.ai',
      rating: 4.9,
      reviewsCount: 1290,
      iconUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Pro Search multi-step reasoning and dynamic query expansion',
        'Direct inline verifiable source citations from reputable publications',
        'Model switcher including Claude 3.5 Sonnet, GPT-4o, and Sonar',
        'Collections workspace organizing research threads and uploaded PDF papers',
      ]),
      useCases: JSON.stringify([
        'Deep competitive intelligence and market trend synthesis',
        'Fact-checking news reports and technical documentation lookup',
        'Academic literature reviews with direct link verification',
      ]),
      tags: JSON.stringify(['Search Engine', 'Research', 'Citations', 'Answer Engine', 'Freemium']),
    },
    {
      name: 'Consensus',
      slug: 'consensus-ai',
      tagLine: 'AI search engine extracting evidence-based insights from 200M+ research papers',
      description: 'Consensus is an academic search engine that uses AI to extract and summarize findings directly from over 200 million peer-reviewed scientific papers. It features the Consensus Meter to quantify scientific agreement on contested topics.',
      fullDescription: 'Consensus is an academic search engine that uses AI to extract and summarize findings directly from over 200 million peer-reviewed scientific papers. It features the Consensus Meter to quantify scientific agreement on contested topics.',
      category: 'Deep Research',
      pricing: 'Freemium',
      websiteUrl: 'https://consensus.app',
      url: 'https://consensus.app',
      rating: 4.8,
      reviewsCount: 570,
      iconUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Consensus Meter measuring percentage of scientific agreement (Yes/No/Possible)',
        'Synthesizes findings across 200M+ peer-reviewed scientific papers',
        'Study Quality Indicators highlighting sample size, rigor, and methodology',
        'Direct citation export to Zotero, Mendeley, and BibTeX',
      ]),
      useCases: JSON.stringify([
        'Medical and health evidence verification for practitioners',
        'Scientific literature reviews for academic dissertations',
        'R&D product formulation and ingredient efficacy research',
      ]),
      tags: JSON.stringify(['Academic', 'Science', 'Peer Reviewed', 'Research', 'Freemium']),
    },
    {
      name: 'Semantic Scholar',
      slug: 'semantic-scholar',
      tagLine: 'Free, AI-powered scientific paper search and discovery by AI2',
      description: 'Developed by the Allen Institute for AI, Semantic Scholar uses machine learning to understand the scientific literature, providing automated paper summaries, highly influential citation graphs, and author research feeds for free.',
      fullDescription: 'Developed by the Allen Institute for AI, Semantic Scholar uses machine learning to understand the scientific literature, providing automated paper summaries, highly influential citation graphs, and author research feeds for free.',
      category: 'Deep Research',
      pricing: 'Free',
      websiteUrl: 'https://semanticscholar.org',
      url: 'https://semanticscholar.org',
      rating: 4.9,
      reviewsCount: 830,
      iconUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'TLDR one-sentence automated scientific paper summaries',
        'Highly Influential Citations distinguishing meaningful citations from casual mentions',
        'Semantic Reader with interactive in-PDF author and citation tooltips',
        '100% free and open non-profit research initiative by AI2',
      ]),
      useCases: JSON.stringify([
        'Accelerating academic literature discovery across AI, biology, and physics',
        'Tracking citation impact and research trajectory of prominent scientists',
        'Discovering foundational methodology papers in emerging technical fields',
      ]),
      tags: JSON.stringify(['Open Science', 'AI2', 'Academic Research', 'Free', 'Citations']),
    },
    {
      name: 'Scite.ai',
      slug: 'scite-ai',
      tagLine: 'Smart citations evaluating whether research papers support or contrast claims',
      description: 'Scite uses deep learning to classify citation statements in scientific literature, showing whether a paper provides supporting or contrasting evidence for any given scientific claim.',
      fullDescription: 'Scite uses deep learning to classify citation statements in scientific literature, showing whether a paper provides supporting or contrasting evidence for any given scientific claim.',
      category: 'Deep Research',
      pricing: 'Paid',
      websiteUrl: 'https://scite.ai',
      url: 'https://scite.ai',
      rating: 4.8,
      reviewsCount: 460,
      iconUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
      featured: true,
      verified: true,
      features: JSON.stringify([
        'Smart Citations categorizing context as Supporting, Mentioning, or Contrasting',
        'Scite Assistant answering questions with verified peer-reviewed paper excerpts',
        'Reference Check verifying whether bibliographies cite retracted papers',
        'Browser extension showing smart citations on PubMed and Google Scholar',
      ]),
      useCases: JSON.stringify([
        'Verifying whether scientific hypotheses have been replicated or refuted',
        'Systematic literature auditing for pharmaceutical and medical research',
        'Preventing the citation of retracted or discredited scientific studies',
      ]),
      tags: JSON.stringify(['Smart Citations', 'Peer Review', 'Academic', 'Verification', 'Paid']),
    },
    {
      name: 'ResearchRabbit',
      slug: 'research-rabbit',
      tagLine: 'The Spotify for academic papers with interactive citation maps and alerts',
      description: 'ResearchRabbit reimagines literature search with visual interactive citation networks. Discover related academic papers, follow researcher collaborations, and receive personalized recommendations for free.',
      fullDescription: 'ResearchRabbit reimagines literature search with visual interactive citation networks. Discover related academic papers, follow researcher collaborations, and receive personalized recommendations for free.',
      category: 'Deep Research',
      pricing: 'Free',
      websiteUrl: 'https://researchrabbitapp.com',
      url: 'https://researchrabbitapp.com',
      rating: 4.8,
      reviewsCount: 390,
      iconUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
      icon: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
      featured: false,
      verified: true,
      features: JSON.stringify([
        'Interactive 2D graph visualizations of paper citations and co-authorships',
        'Zotero bidirectional sync for saved collections and notes',
        'Personalized research alerts when new connected papers are published',
        'Completely free for researchers, students, and academics worldwide',
      ]),
      useCases: JSON.stringify([
        'Visualizing research lineages and seminal papers in a new discipline',
        'Comprehensive bibliography compilation for thesis literature reviews',
        'Staying current on specialized scientific research topics',
      ]),
      tags: JSON.stringify(['Citation Graph', 'Academic', 'Zotero', 'Free', 'Literature Search']),
    },
  ];

  console.log(`Inserting ${toolsData.length} comprehensive tools...`);

  for (const tool of toolsData) {
    const createdTool = await prisma.tool.create({
      data: tool,
    });

    // Add high quality realistic reviews
    await prisma.review.create({
      data: {
        toolId: createdTool.id,
        userId: demoUser.id,
        rating: 5,
        title: 'Essential tool in our engineering stack',
        content: `We integrated ${tool.name} into our daily workflows and it has cut turnaround time significantly. The AI precision and integration reliability are unmatched.`,
      },
    });

    // Add a demo bookmark
    if (tool.featured) {
      await prisma.bookmark.create({
        data: {
          toolId: createdTool.id,
          userId: demoUser.id,
        },
      });
    }
  }

  console.log('Database seeding successfully finished!');
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
